apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dnszones.crd.yaml
  - arecords.crd.yaml
  - aaaarecords.crd.yaml
  - txtrecords.crd.yaml
  - cnamerecords.crd.yaml
  - mxrecords.crd.yaml
  - nsrecords.crd.yaml
  - srvrecords.crd.yaml
  - caarecords.crd.yaml
  - bind9instances.crd.yaml
