apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind9-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bind9-controller-role
subjects:
  - kind: ServiceAccount
    name: bind9-controller
    namespace: dns-system
