apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind9-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bind9-operator-role
subjects:
- kind: ServiceAccount
  name: bind9-operator
  namespace: dns-system
